type: rpm-ostree
install:
# environment
  - polkit
  - xdg-user-dirs
  - dbus-tools
  - dbus-daemon
  - google-noto-emoji-fonts

# sound
  - wireplumber
  - pipewire

# networking
  - bluez
  - bluez-tools
  - blueman
  - openssh-server
  - systemd-networkd
  - wpa_supplicant

# display
  - wlr-randr

# theme and GUI
  - gnome-themes-extra
  - gnome-icon-theme
  - paper-icon-theme

# kiosk support
  - chromium
  - squeekboard
  - firefox